# Generated by Django 3.2.18 on 2024-08-28 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('usertype', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='music_teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('CATEGORY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_teacher_booking_app.category')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_teacher_booking_app.login')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_teacher_booking_app.login')),
            ],
        ),
        migrations.CreateModel(
            name='request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('MUSIC_TEACHER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_teacher_booking_app.music_teacher')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_teacher_booking_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('MUSIC_TEACHER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_teacher_booking_app.music_teacher')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_teacher_booking_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('payment_method', models.CharField(max_length=100)),
                ('payment_status', models.CharField(max_length=100)),
                ('REQUEST', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_teacher_booking_app.request')),
            ],
        ),
        migrations.CreateModel(
            name='own_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(max_length=100)),
                ('CATEGORY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_teacher_booking_app.category')),
                ('MUSIC_TEACHER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_teacher_booking_app.music_teacher')),
            ],
        ),
        migrations.CreateModel(
            name='class_new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.CharField(max_length=100)),
                ('endtime', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('MUSIC_TEACHER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_teacher_booking_app.music_teacher')),
            ],
        ),
        migrations.CreateModel(
            name='allocate_time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('CLASS_NEW', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_teacher_booking_app.class_new')),
                ('REQUEST', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_teacher_booking_app.request')),
            ],
        ),
    ]
