# Generated by Django 3.2.18 on 2024-08-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_teacher_booking_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music_teacher',
            name='image',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
