# Generated by Django 3.2.18 on 2024-08-28 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_teacher_booking_app', '0002_music_teacher_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music_teacher',
            name='CATEGORY',
        ),
    ]
