# Generated by Django 3.2.18 on 2024-08-29 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_teacher_booking_app', '0003_remove_music_teacher_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='USER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='music_teacher_booking_app.user'),
            preserve_default=False,
        ),
    ]
