# Generated by Django 3.2.18 on 2024-08-29 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_teacher_booking_app', '0004_feedback_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class_new',
            old_name='date',
            new_name='day',
        ),
    ]
