# Generated by Django 3.2.18 on 2024-08-29 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_teacher_booking_app', '0005_rename_date_class_new_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='date',
        ),
    ]
