# Generated by Django 3.2.18 on 2024-08-29 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_teacher_booking_app', '0006_remove_request_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='own_category',
            old_name='payment_status',
            new_name='fees',
        ),
    ]
