# Generated by Django 3.2.18 on 2024-08-29 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_teacher_booking_app', '0007_rename_payment_status_own_category_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='class_new',
            name='OWN_CATEGORY',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='music_teacher_booking_app.own_category'),
            preserve_default=False,
        ),
    ]
