# Generated by Django 3.2.18 on 2024-09-01 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_teacher_booking_app', '0008_class_new_own_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='request',
            new_name='requests',
        ),
        migrations.RenameField(
            model_name='allocate_time',
            old_name='REQUEST',
            new_name='REQUESTS',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='REQUEST',
            new_name='REQUESTS',
        ),
    ]
