# Generated by Django 3.2.18 on 2024-09-01 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_teacher_booking_app', '0009_auto_20240901_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requests',
            name='MUSIC_TEACHER',
        ),
        migrations.AddField(
            model_name='requests',
            name='OWN_CATEGORY',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='music_teacher_booking_app.own_category'),
            preserve_default=False,
        ),
    ]
